# Generated by Django 3.1.6 on 2021-02-05 21:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychotherapist',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('photo_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PsychotherapistRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parsed_at', models.DateTimeField()),
                ('raw_data', models.JSONField()),
            ],
        ),
    ]
